### ISSUE TITLE
atom 0.5.0 breaks enaml

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/atom#100]
The current release of atom does not work with the current release of enaml (see https://github.com/inkcut/inkcut/issues/238).

Can you please pull the 0.5.0 release until a compatible version of enaml is also released or release a compatible version of enaml?

**Comment by MatthieuDartiailh** [comment]
I am in the process of releasing the new version of enaml but the focus tracking bug has delayed it slightly. Sorry for the inconvenience. I will publish the release by Wednesday evening at the latest.

**Comment by MatthieuDartiailh** [comment]
The new version of enaml is now available on pypi (as source and wheels). Once again sorry for the inconvenience.

**Comment by frmdstryr** [comment]
Well that was quick, thank you!
