### ISSUE TITLE
Custom initialization of Atom members

### ISSUE THREAD

**Issue by adigitoleo** [nucleic/atom#106]
Hi, 

I've been enjoying playing with atom/enaml for python desktop apps, but I can't find docs on how to do things like this:

```python
from atom.api import Atom, Int

class Square(Atom):
    size = Int(2)
    area = size**2  # Doesn't work.
```

Is it possible? Should I override `__init__` , or are there ways to set up constructor factory methods?

Cheers

**Comment by MatthieuDartiailh** [comment]
You can do the following to override how the default value is computed:
```python
class Square(Atom):
     size = Int(2)
     area = Int()

    def _default_area(self):
        return self.size**2

```
This kind of customization is described in https://atom.readthedocs.io/en/latest/basis/mangled_methods.html . Let me know if you have a suggestion to improve the documentation.

**Comment by adigitoleo** [comment]
@MatthieuDartiailh 
Well, this is embarrassing. Going back over my code I see that I tried that method as well, but decided to name it `_default_area_value` for some reason. Maybe I got confused by the Anatomy example (https://atom.readthedocs.io/en/latest/basis/basis.html) but probably I just didn't read it well :laughing:
