### ISSUE TITLE
Link to enaml broken; disambiguate from Enthought Enaml?

### ISSUE THREAD

**Issue by metaperl** [nucleic/atom#111]
The [welcome page](https://atom.readthedocs.io/en/latest/) has the text "default model binding behaviour for the Enaml UI framework." but the Enaml link is broken.

Also a quick question: is this enaml different from [this one](https://docs.enthought.com/enaml/)?

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. I fixed the link (https://github.com/nucleic/atom/commit/d425de1750805e04402db15b79be92a0161d8f7a) and regarding your second point @sccolbert started enaml at Enthought but then kept developing it while working at JP Morgan. The currently maintained version of Enaml is the one under this organization. The Enthought version is way out of date.
