### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/atom#135]
The release 0.7.0.rc1 is on PyPI. I will delay the final release because it appears I may have some Qt issues for python 3.10 on enaml (but I will have to double check). If you have to time to test this (with enaml main) you are very much welcome to do so.

**Comment by MatthieuDartiailh** [comment]
The next RC for atom is on PyPI. I tagged a rc for enaml but did not upload wheels for it. Let me know if they are needed.

**Comment by MatthieuDartiailh** [comment]
Actually I found one hard bug in Tuple, that I will fix and some sub optimal behavior of type hints now that things List(Optional[int]) are meaningful. This may be harder to fix and I may defer till after 0.7.0 even though it would be a shame.

**Comment by MatthieuDartiailh** [comment]
The tuple fix is addressed in #140 and the issue with `List(Optional[int])` turned out not be fixable in the type system itself. I added some notes to the docs basically suggesting to prefer using proper members directly in that case if static type checking is of interest.

**Comment by frmdstryr** [comment]
Thank you!

**Comment by MatthieuDartiailh** [comment]
You are welcome !
