### ISSUE TITLE
ENH Request: Rise for _default_x,  _observe_x  _validate_x if x is not an member

### ISSUE THREAD

**Issue by Tillsten** [nucleic/atom#137]
One of my most common bugs is forgetting to rename one of these methods after changing the member name, or just mistyping the name. Hence I would love to have a check for that. Alternativly, allowing the attrs `@x.default` aproach to mark the default factory would also be a solution.

**Comment by MatthieuDartiailh** [comment]
For backward compatibility reason, I would make that a warning. But I agree it makes sense. I have to finish PR #136 to be able to release 0.7.0 and won't have time to work on this myself but I will happily review a PR and this could be included in 0.7.0.

Regarding alternative ways to specify the magic methods, I would prefer to defer the discussion till after the release.

**Comment by MatthieuDartiailh** [comment]
@Tillsten please have a look at #139 (based on #136 so only check the last commit)

**Comment by MatthieuDartiailh** [comment]
ping @Tillsten

**Comment by Tillsten** [comment]
Thanks a lot for this addition!
