### ISSUE TITLE
Proposal: Allow members to selectively set default change event types generated

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/atom#154]
By default atom generates and sends `"created"` event for every member. 

If you profile an app, the [declarative_change_handler](https://github.com/nucleic/enaml/blob/main/enaml/core/declarative_meta.py#L49) causes every widget's `_update_proxy` to be called.  In all default cases this change is discarded leading to lots of function calls/checking that are ultimately ignored.  

A few second benchmark of an enaml-web page generates ~1.5m `_update_proxy` calls (6th most called overall) and which accounts for about ~10% of the init time and could be completely avoided as the proxy is not yet active.

With that said, It'd be nice to have a way to opt in/out of events at the atom level to avoid overhead. Something like:

```python
class A(Atom):
    style = d_(Int(change_types=("update", "delete")))

```

The Member `modes` currently reserves 1 byte for each mode but only the validate mode uses more than 16 values.  

If the other modes were packed into 4 bits there would be room to add a "set_change_types" to selectively enable/disable the default change event types.

Any thoughts? I can work on implementing it.

**Comment by MatthieuDartiailh** [comment]
I have not though about it much but we could also want to filter per observer rather than per member. This way enaml could simply say it does not care about creation event.

**Comment by frmdstryr** [comment]
> filter per observer rather than per member

That makes sense. I suppose a field could need to be added to `ObserverPool::Topic`?

**Comment by MatthieuDartiailh** [comment]
I did not check the code. Feel free to start experimenting in that direction if you want.

**Comment by frmdstryr** [comment]
Changing a single flag gives about a 15% speedup :+1: .
