### ISSUE TITLE
Atom has different method resolution order for members

### ISSUE THREAD

**Issue by jolos** [nucleic/atom#164]
Best explained with a piece of code:
Plain python has the following behavior:

```python

class A:
    a = "a"


class B:
    b = "b"


class AB(A, B):
    pass


class A2(A):
    a = "a2"

class C(AB, A2):
    pass


print(C().a) # => "a2"
```

while atom has the following behavior.

```python
from atom.api import Atom, Str


class A(Atom):
    a = Str("a")


class B(Atom):
    b = Str("b")


class AB(A, B):
    pass

class A2(A):
    a = Str("a2")

class C(AB, A2):
    pass

print(C().a) # => "a"
```

If my understanding is correct, this is because upon cloning the cloned member gets assigned to the class being created https://github.com/nucleic/atom/blob/f0997b31562724e2304ef34e3ab7d5b12cccf9b6/atom/atom.py#L399-L405

Because of this the following lines will also include the cloned members even when they were not defined by the user:
https://github.com/nucleic/atom/blob/f0997b31562724e2304ef34e3ab7d5b12cccf9b6/atom/atom.py#L340-L344

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. I will look into it but I cannot say when. Feel free to ping me.
