### ISSUE TITLE
Atom class with Dict member never frees memory

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/atom#202]
I spent several days figuring trying to figure out why my apps keep creeping up memory. Finally traced it down to the `Dict` member. 

Please run the following and watch it consume all the memory on your system... The `Typed(dict, ())` version uses about 5k memory, the Dict version used up 19GB and froze my system....

```python
from atom.api import Atom, Dict, Typed


class Foo(Atom):
    data = Dict() # DOOM
    # data = Typed(dict, ()) # Works fine

def main():
    while True:
        foo = Foo()
        foo.data = {"a": 0}
        del foo

if __name__ == '__main__':
    main()

```

I have not checked the other container members (will check next week).

**Comment by frmdstryr** [comment]
Comparing to the AtomList_dealloc does the AtomDict_dealloc also need

```
    PyObject_GC_UnTrack( self );
    delete self->pointer;
    self->pointer = 0;
```

**Comment by sccolbert** [comment]
I think the leak is the `self->pointer` field. I don't recall adding the
`PyObject_GC_UnTrack` call to `AtomList`, so that may have been Mathieu.

**Comment by MatthieuDartiailh** [comment]
I agree with the diagnostic here. I made minor changes to the PR to appease the linters and I will merge an publish as soon as the CIs are green.

**Comment by frmdstryr** [comment]
Thanks Matthieu!
