### ISSUE TITLE
atom.core ImportError

### ISSUE THREAD

**Issue by DenisDubovitskiy** [nucleic/atom#61]
Hi, I`m trying to import atom.data, just like in Google docs (https://developers.google.com/google-apps/contacts/v3/) and Always getting the same error:
```python
Traceback (most recent call last):
  File "/Users/Denis/Development/contacts/contacts/client.py", line 4, in <module>
    import atom.data
  File "/Users/Denis/Development/contacts/env/lib/python2.7/site-packages/atom/data.py", line 24, in <module>
    import atom.core
ImportError: No module named core

Process finished with exit code 1
```
Here is my code:

```python
from __future__ import division
from __future__ import absolute_import
import atom.data
```

Python 2.7.10. I also tried to install package with pip and setup.py. What did I do wrong? There is only one solution, that works for me: http://stackoverflow.com/questions/30740786/import-error-with-atom-module

PS: I`m sorry for my bad English

**Comment by sccolbert** [comment]
Google's Atom library is different from this project. Ensure you've installed the right one.

This is probably the library you're looking for:
https://pypi.python.org/pypi/gdata.py/1.0.2
