### ISSUE TITLE
Numpy array

### ISSUE THREAD

**Issue by conorfleming** [nucleic/atom#62]
Is Atom compatible with Numpy arrays? I would like to do something like the example below.

    from atom.api import NumpyArray
    
    class TrainHistory(Atom):
        time = NumpyArray()
        location = NumpyArray()

**Comment by dwillmer** [comment]
You can use `Value` to store arbitrary objects:
```
class TrainHistory(Atom):
    time = Value()
    location = Value()
```
or alternatively you can enforce the type using `Typed`

**Comment by conorfleming** [comment]
Brilliant, thanks for the help.
