### ISSUE TITLE
Installing with pip fails

### ISSUE THREAD

**Issue by JohnHollowell** [nucleic/atom#66]
when I try "pip install atom" as administrator on Win10, it errors out:

`Command ""c:\program files (x86)\python35-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\John\\AppData\\Local\\Temp\\pip-build-3m_c0r5p\\atom\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\John\AppData\Local\Temp\pip-l8e3y4fb-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\John\AppData\Local\Temp\pip-build-3m_c0r5p\atom\`

full log: https://puu.sh/st2gc.txt

**Comment by MatthieuDartiailh** [comment]
Atom needs a C compiler to be properly intalled via pip as no wheels are currently distributed. Depending on the Python version you are using it may be more or less complicated to setup one properly. Another option is to use a distribution such that Anaconda that provides pre-compiled versions.
