### ISSUE TITLE
Question: AtomList gc flags

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/atom#69]
Looking at the code for atomlist I noticed it does not set the flags used for containers (while typedlist in 1.0.0.dev set it). From my understanding that could prevent gc collection in the case of cyclic references. If it is so it would worth setting that flag and adding tp_traverse and tp_clear. Could you comment about the pertinences of such changes @sccolbert ?

**Comment by sccolbert** [comment]
Both of those objects are subclasses of the builtin `list` type, so they inherit the `tp_clear` and `tp_traverse` slots of the base class. So, you don't have to worry about circular refs within the list.

It *does* seem that I overlooked the `validator` and `member` struct fields in `AtomList` and `AtomCList` wrt to gc traversing. However, it's unlikely that those fields would ever be a part of a reference cycle, so it should be a non-issue in practice.

**Comment by MatthieuDartiailh** [comment]
Thanks for the clarification. I am currently tracking some complex reference cycles in my application and I was worried it might be related to this but it obviously is not. However, if I ever get to back-port some of the feature of 1.0.0 I will be sure to fix the corner case.

**Comment by MatthieuDartiailh** [comment]
Would you mind leaving this open (with possibly a different title), so that I do not forget to fix the corner case when I find some spare time ?

**Comment by MatthieuDartiailh** [comment]
Thanks

**Comment by MatthieuDartiailh** [comment]
Has been addressed at one point.
