### ISSUE TITLE
Items appended to List objects do not trigger informers. Make this clearer.

### ISSUE THREAD

**Issue by Julian-O** [nucleic/atom#80]
Consider this (untested example) code:

```
class Owner(atom):
    name = Str()
    pets = List()
```

If John gets a new dog, I can add it with this line:

` john.pets = john.pets + ["Fido"]`

an observer will be notified of the change.

However, if I add it with this line:

`john.pets.append("Fido")`

a new list will be created, the original list won't change, and the observer will not be informed.

I believe this is working as was originally designed, but this subtlety is not clear. It is a trap for newbies that I fell into and wasted a few hours on trying to work out why my Enaml GUI wasn't updating.

If it doesn't make sense to make this an observer trigger, then at least add warnings in the comments and documentation to save others from falling for the same trap.

**Comment by sccolbert** [comment]
Use a `ContainerList` instead of a `List`:

https://github.com/nucleic/atom/blob/master/atom/containerlist.py#L13

**Comment by sccolbert** [comment]
The notification which comes through will contain details about how the container list was changed.

**Comment by sccolbert** [comment]
Example: https://github.com/nucleic/atom/blob/master/examples/api/containers.py#L24
