### ISSUE TITLE
More descriptive errors for Instance members

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/atom#89]
Currently on python 2.7 a TypeError shows a detailed description of what the error is:

```python-traceback
  File "some/path/models.py", line 505, in clone
    clone = Job(**self.members())
TypeError: The 'copy_spacing' member on the 'Job' object must be of type 'list'. Got object of type 'ContainerList' instead.
```

On 3.6 the error is much less useful,

```python-traceback
  File "some/path/models.py", line 505, in clone
    clone = Job(**self.members())
TypeError: invalid instance type
```

Could the same error reporting from 2.7 be used on 3+?

**Comment by MatthieuDartiailh** [comment]
Can you confirm that the difference in the error message message is simply related to the order in which the members are assigned to ? If it is so could you please edit the title of the issue since it seems to be simply related to the `Instance` member and not to the Python version.

**Comment by frmdstryr** [comment]
Oh sorry, changed the title. After adding in #90 it is showing a different member, so the order is changing, good call. 

In either case it would really be helpful to at indicate which member of which member is failing validation for Instance members (and Subclass while we're at it).

**Comment by frmdstryr** [comment]
This is great, thank you!
