### ISSUE TITLE
post-setattr for Dict

### ISSUE THREAD

**Issue by mgrrx** [nucleic/atom#94]
I have the following code:

```
import atom.api as atom

class Counter(atom.Atom):

    content = atom.Dict(atom.Str(), atom.Int())

    @atom.cached_property
    def sum(self):
        return sum(self.content.values())

    def _post_setattr_content(self, old, new):
        print("old", old)
        print("new", new)
        self.get_member('content').reset(self)

def test_counter():
    s = Counter()
    assert s.sum == 0
    s.content["foo"] = 1
    assert s.sum == 1
```
But unfortunately _post_setattr_content is not called when the dict is updated. Is there an alternative way to trigger the reset when the dict is updated?

**Comment by MatthieuDartiailh** [comment]
post-setattr are called when you actually set the member value. Here you are simply updating the dictionary in place. There has been some requests to provide a ContainerDict similar to the ContainerList, but those actually are more troublesome than anything in the long run (notifications tend to be too granular) and discussions that happened some years ago when @sccolbert was working on a 1.0.0 (that was never completed) concluded that those should be rather kept out (https://groups.google.com/forum/#!topic/enaml/6r82qlFLWdk).

You can attack the problem differently, either create a wrapper with a dict like interface that will be responsible for notifications (and use a combination of Coerced and post-setattr to set up your notifications) or make content private and provide methods to access to it.
