### ISSUE TITLE
Using like lazy-initing dict equivalent?

### ISSUE THREAD

**Issue by byaka** [nucleic/atom#95]
Is it possible? After reading docs i'm thinking - no (without major rewriting). But maybe i miss something?

This useful when i have huge 'tree' of dicts and some of them newer will have childs - but ofc eat memory.

**Comment by MatthieuDartiailh** [comment]
I am not sure I fully follow your use case. You can use use a `_default_xxx` method to initialize your member this will be called only if you access the member. If you want a lazy dict you can subclass Python builtin dict and implement `__missing__`. In which case you could use a `Typed` member instead of a `Dict` member. Does that help ?

**Comment by byaka** [comment]
Thx for answer, @MatthieuDartiailh !
But now, i have another case.
I have structure like this
```python
myTree={
	'l1-k1':{
		'l2-k1':{},
		'l2-k2':{},
	},
	'l1-k2':{},
	'l1-k3':{
		'l2-k1':{},
		'l2-k2':{
			'l3-k1':{},
			'l3-l2':{},
		},
		'l2-k3':{},
		'l2-k4':{},
	}
}
```
and this 'tree' have huge size (for now in 300kk of dicts and growing). I dont know which level will have childs and which not, also any of empty level can be filled in future. But usually i have 55% of empty dicts (summary on all levels).
But each empty dict eat 48kb of memory.

So i want to have lazy-inited empty dicts, which will be inited only on adding elements and eat lower memory while not inited. But all my attempts do this on python   have no results - instances of custom classes eat more memory than empty dict.

**Comment by MatthieuDartiailh** [comment]
I do not have a perfect solution but here are my thoughts:
- the lowest cost in term of re-writing could be to switch from Python builtin dict to atom sortedmap. On a 64 bits python, an empty dict takes 240 bytes, an empty sortedmap 72. And generally speaking sortedmap is smaller than dict. This is probably the best solution.
- use a custom Atom class wrapping a Dict or Typed member. Each instance is 72 bytes but you add 240 bytes once you create the dict. I am not sure your structure is sparse enough to win anything and the cost in term of code writing is much higher.

Let me know what you think.

**Comment by byaka** [comment]
@MatthieuDartiailh 
thank you for ideas, this very interesting! Ill think about it - first need alot of rewriting but second looks like what i want if i understand you correctly. Ill try it asap and let you know.

p.s.
lol i dont know how i matched 48kb, was sleeppy or stupid.

**Comment by byaka** [comment]
@MatthieuDartiailh thanks again for your help!
i'm not sure that i use Atom in right way, but it works and eat x3 time lower memory on empty dicts.
[testLazyInstances.py.zip](https://github.com/nucleic/atom/files/3266636/testLazyInstances.py.zip)

**Comment by MatthieuDartiailh** [comment]
Happy you found a way to make it work for you.
