### ISSUE TITLE
List and atomclist don't implement get

### ISSUE THREAD

**Issue by Annakan** [nucleic/atom#96]
So there is not way to safely probe an index and get a default value if needed.

There is default values on containers but container creation is not always in our hand to specify a default value.

**Comment by MatthieuDartiailh** [comment]
Actually no. Python does not provide any mechanism of the sort for lists (contrary to dict) and it would actually be kind of weird: what to do if a user request the element at index 10 of a list of length 2 ? Create all the missing intermediate elements ?
Atom focuses on providing typed version of Python containers but I would not try to add a mechanism similar to the one you describe.

**Comment by Annakan** [comment]
My bad you are right, I am trying to make table.items[loop_index] in an enaml looper where the looped on container can have element deleted and starting to go off the rail (lat hours not helping).
